site_name: MCP Agent Stack
nav:
  - Home: index.md
  - Architecture: architecture.md
  - Deployment: DEPLOYMENT.md
  - Production Ready Summary: PRODUCTION_READY_SUMMARY.md
markdown_extensions:
  - admonition
  - codehilite
  - toc
